### ISSUE TITLE
Error in hodgkin_huxley.py

### ISSUE THREAD

**Issue by aviralg** [nsdf/nsdf#39]
```bash
$ python hodgkin_huxley.py
```
```python
Traceback (most recent call last):
  File "hodgkin_huxley.py", line 112, in <module>
    hh_vm()
  File "hodgkin_huxley.py", line 37, in hh_vm
    'Upinder Bhalla']})
  File "/tmp/nsdf/nsdf/nsdfwriter.py", line 270, in set_properties
    self._fd.attrs['tstart'] = properties['tstart'].isoformat()
AttributeError: 'str' object has no attribute 'isoformat'
```

**Comment by subhacom** [comment]
Fixed in commit 0548ff5
